# Generated by Django 4.2.6 on 2023-10-16 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='otp_created',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
