# Generated by Django 4.2.6 on 2023-10-16 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_userprofile_otp_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='otp_created',
            new_name='otp_created_on',
        ),
    ]
