# Generated by Django 4.2.6 on 2023-10-16 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_rename_otp_created_userprofile_otp_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='otp_requested',
        ),
    ]
