# Generated by Django 4.2.6 on 2023-10-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_remove_userprofile_otp_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_rest',
            field=models.BooleanField(default=False),
        ),
    ]
