# Generated by Django 4.2.6 on 2023-10-17 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_userprofile_password_rest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='password_rest',
            new_name='password_reset',
        ),
    ]
