# Generated by Django 4.2.6 on 2023-10-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_alter_log_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='number_of_users',
        ),
        migrations.AlterField(
            model_name='log',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
