# Generated by Django 4.2.6 on 2023-10-18 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_remove_log_number_of_users_alter_log_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='user_id',
            new_name='users_involved',
        ),
    ]
