# Generated by Django 4.2.6 on 2023-10-18 10:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logs', '0007_rename_user_id_log_users_involved'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='splitted_among',
            field=models.ManyToManyField(related_name='all_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='log',
            name='users_involved',
            field=models.ManyToManyField(related_name='all_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
