# Generated by Django 4.2.6 on 2023-10-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0008_item_splitted_among_alter_log_users_involved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
