# Generated by Django 4.2.6 on 2023-10-20 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0010_log_log_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='log_hash',
        ),
    ]
